# SPDX-FileCopyrightText: 2026 MistVVK and the XeStrata contributors
# SPDX-License-Identifier: LGPL-3.0-or-later
# flake8 for XeStrata's Python (tools/lint/run.sh): the code keeps lines up to 120 characters
[flake8]
max-line-length = 120
