// SPDX-FileCopyrightText: 2026 MistVVK and the XeStrata contributors
// SPDX-License-Identifier: LGPL-3.0-or-later
// HTML Tidy for the web app's page (tools/lint/run.sh): the icon placeholders are empty <span>s on purpose
drop-empty-elements: no
