# SPDX-FileCopyrightText: 2026 MistVVK and the XeStrata contributors
# SPDX-License-Identifier: LGPL-3.0-or-later
# cmake/StrataCuda.cmake - the contrib build's CUDA toolkit and NVIDIA architectures.
#
# intel/llvm's clang takes the first CUDA toolkit on its own list (/usr/local/cuda before Debian's /usr/lib/cuda) and
# CMake's FindCUDA the nvcc on PATH, whatever the GPUs; a PC can have several (a distribution's and NVIDIA's).  Each
# toolkit found is tried here: the code it builds for each of this PC's NVIDIA GPUs (the GPU's architecture or the
# newest older one it builds: CUDA 13 builds no Volta code, CUDA 12.4 none for an RTX 50), whether it has cuBLAS, and
# its PTX version lowered to the driver's when the driver is older (else the driver cannot load it).  The one taken
# builds code for the most GPUs, then the newest architectures, then has cuBLAS, then is the newest; the NVIDIA code
# and oneMath's cuBLAS backend both use it.

# Whether `flags` (a list) build and link a SYCL kernel; remembered in the cache as `name`.
function(strata_sycl_compiles flags name out)
  if(NOT DEFINED ${name})
    set(src "${CMAKE_BINARY_DIR}/strata_sycl_probe.cpp")
    if(NOT EXISTS "${src}")
      file(WRITE "${src}" "#include <sycl/sycl.hpp>\nint main() { sycl::queue q; q.single_task([] {}); }\n")
    endif()
    message(CHECK_START "Building a SYCL kernel with ${flags}")
    # a result variable of its own: try_compile caches it, and an older one would answer this check
    try_compile(${name}_result "${CMAKE_BINARY_DIR}/strata_sycl_probe" SOURCES "${src}"
                COMPILE_DEFINITIONS -fsycl ${flags} LINK_OPTIONS -fsycl ${flags})
    set(ok "${${name}_result}")
    if(ok)
      message(CHECK_PASS "yes")
    else()
      message(CHECK_FAIL "no")
    endif()
    set(${name} "${ok}" CACHE INTERNAL "")
  endif()
  set(${out} "${${name}}" PARENT_SCOPE)
endfunction()

# The CUDA version the installed driver supports (12040 for 12.4), or "" without a driver.
function(strata_cuda_driver_version out)
  file(WRITE "${CMAKE_BINARY_DIR}/strata_cuda_driver.cpp"
       "#include <dlfcn.h>\n#include <stdio.h>\nint main(void) { void* h = dlopen(\"libcuda.so.1\", RTLD_NOW);\n"
       "  int (*f)(int*) = h ? (int (*)(int*)) dlsym(h, \"cuDriverGetVersion\") : 0;\n  int v = 0;\n"
       "  if (!f || f(&v)) return 1;\n  printf(\"%d\", v);\n  return 0;\n}\n")
  try_run(rc built "${CMAKE_BINARY_DIR}/strata_cuda_driver" SOURCES "${CMAKE_BINARY_DIR}/strata_cuda_driver.cpp"
          LINK_LIBRARIES ${CMAKE_DL_LIBS} RUN_OUTPUT_VARIABLE version)
  if(built AND rc EQUAL 0 AND version MATCHES "^[0-9]+$")
    set(${out} "${version}" PARENT_SCOPE)
  else()
    set(${out} "" PARENT_SCOPE)
  endif()
endfunction()

# The toolkit folders on this PC: STRATA_CUDA_PATH when it names one, else every one found (real paths, once each).
function(strata_cuda_candidates out)
  if(NOT STRATA_CUDA_PATH STREQUAL "auto")
    set(${out} "${STRATA_CUDA_PATH}" PARENT_SCOPE)
    return()
  endif()
  file(GLOB numbered LIST_DIRECTORIES true /usr/local/cuda-* /opt/cuda-*)
  set(dirs "$ENV{CUDA_PATH}" "$ENV{CUDA_HOME}" "$ENV{CUDA_ROOT}" ${numbered} /usr/local/cuda /opt/cuda /usr/lib/cuda)
  find_program(nvcc_on_path nvcc NO_CACHE)
  if(nvcc_on_path)
    get_filename_component(nvcc_dir "${nvcc_on_path}" REALPATH)
    get_filename_component(nvcc_dir "${nvcc_dir}" DIRECTORY)
    get_filename_component(nvcc_dir "${nvcc_dir}" DIRECTORY)
    list(APPEND dirs "${nvcc_dir}")
  endif()
  set(found "")
  foreach(dir IN LISTS dirs)
    if(dir AND IS_DIRECTORY "${dir}")
      get_filename_component(r "${dir}" REALPATH)
      file(GLOB libdevice "${r}/nvvm/libdevice/libdevice*.bc")   # what clang needs of a toolkit
      if(libdevice)
        list(APPEND found "${r}")
      endif()
    endif()
  endforeach()
  list(REMOVE_DUPLICATES found)
  set(${out} "${found}" PARENT_SCOPE)
endfunction()

# The toolkit's version ("12.4"): its version.json, else its nvcc (Debian's is /usr/bin/nvcc for /usr/lib/cuda).
function(strata_cuda_version dir out)
  set(version "")
  if(EXISTS "${dir}/version.json")
    file(READ "${dir}/version.json" j)
    string(REGEX MATCH "\"cuda\"[^}]*\"version\" *: *\"([0-9]+)\\.([0-9]+)" m "${j}")
    if(m)
      set(version "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}")
    endif()
  endif()
  if(NOT version)
    set(nvcc "${dir}/bin/nvcc")
    if(NOT EXISTS "${nvcc}" AND EXISTS /usr/bin/nvcc)
      set(nvcc /usr/bin/nvcc)
    endif()
    if(EXISTS "${nvcc}")
      execute_process(COMMAND "${nvcc}" --version OUTPUT_VARIABLE o ERROR_QUIET)
      string(REGEX MATCH "release ([0-9]+)\\.([0-9]+)" m "${o}")
      if(m)
        set(version "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}")
      endif()
    endif()
  endif()
  set(${out} "${version}" PARENT_SCOPE)
endfunction()

# FindCUDA's root for a toolkit: its own folder when its nvcc is there, else /usr (Debian's /usr/lib/cuda).
function(strata_cuda_root dir out)
  if(NOT EXISTS "${dir}/bin/nvcc" AND EXISTS /usr/bin/nvcc)
    set(${out} /usr PARENT_SCOPE)
  else()
    set(${out} "${dir}" PARENT_SCOPE)
  endif()
endfunction()

# Whether the toolkit has cuBLAS (its header and library), which oneMath's cuBLAS backend links.
function(strata_cuda_has_cublas dir out)
  strata_cuda_root("${dir}" root)
  file(GLOB libs "${dir}/lib64/libcublas.so*" "${dir}/lib/libcublas.so*" "${dir}/targets/*/lib/libcublas.so*")
  if(root STREQUAL "/usr")
    file(GLOB more "/usr/lib/*/libcublas.so*" "/usr/lib64/libcublas.so*" "/usr/lib/libcublas.so*")
    list(APPEND libs ${more})
  endif()
  if(libs AND (EXISTS "${dir}/include/cublas_v2.h" OR EXISTS "${root}/include/cublas_v2.h"))
    set(${out} ON PARENT_SCOPE)
  else()
    set(${out} OFF PARENT_SCOPE)
  endif()
endfunction()

# The PTX version clang writes with toolkit `dir` (toolkit_out, "" when clang does not take the toolkit) and the one
# to ask for (out): STRATA_CUDA_PTX, or with "auto" the driver's when the driver is older, else "" (the toolkit's).
function(strata_cuda_ptx dir driver out toolkit_out)
  execute_process(COMMAND ${CMAKE_CXX_COMPILER} -fsycl -fsycl-targets=nvptx64-nvidia-cuda --cuda-path=${dir} -c
                          "${CMAKE_BINARY_DIR}/strata_ptx_probe.cpp" -o /dev/null "-###"
                  OUTPUT_VARIABLE o ERROR_VARIABLE o)
  string(REGEX MATCH "\"\\+ptx([0-9]+)\"" m "${o}")
  set(toolkit_ptx "${CMAKE_MATCH_1}")
  set(${toolkit_out} "${toolkit_ptx}" PARENT_SCOPE)
  set(ptx "${STRATA_CUDA_PTX}")
  if(ptx STREQUAL "auto")
    set(ptx "")
    if(toolkit_ptx AND driver AND driver LESS 13000)
      # clang's table (clang/lib/Driver/ToolChains/Cuda.cpp): CUDA version -> PTX version
      foreach(pair IN ITEMS 12090:88 12080:87 12050:85 12040:84 12030:83 12020:82 12010:81 12000:80 11080:78
                            11070:77 11060:76 11050:75 11040:74 11030:73 11020:72 11010:71 11000:70 10020:65 10010:64)
        string(REPLACE ":" ";" pair "${pair}")
        list(GET pair 0 cuda)
        list(GET pair 1 driver_ptx)
        if(driver GREATER_EQUAL cuda)
          if(driver_ptx LESS toolkit_ptx)
            set(ptx ${driver_ptx})
          endif()
          break()
        endif()
      endforeach()
    endif()
  endif()
  set(${out} "${ptx}" PARENT_SCOPE)
endfunction()

# The code toolkit options `opts` build for `archs` (explicit: all of them or none; else each GPU's own architecture
# or the newest older one).  An architecture SYCL has no name for (nvidia_gpu_sm_120 is not in intel/llvm 7.1.1)
# takes the generic NVIDIA target with that architecture, which one executable can have once: the oldest such GPU's.
# Sets in the caller: _b_built, _b_generic (the architecture built through the generic target, or ""), _b_covered
# (GPUs with code), _b_sum (their architectures' numbers added: newer code, a greater sum).
function(strata_cuda_builds opts archs explicit key)
  set(built "")
  set(generic "")
  set(covered 0)
  set(sum 0)
  set(sorted_archs ${archs})
  list(SORT sorted_archs COMPARE NATURAL)            # the generic target goes to the oldest GPU that needs it
  if(explicit)
    list(TRANSFORM archs PREPEND nvidia_gpu_ OUTPUT_VARIABLE targets)
    list(JOIN targets "," targets)
    string(MD5 akey "${targets}")
    string(SUBSTRING "${akey}" 0 8 akey)
    strata_sycl_compiles("-fsycl-targets=${targets};${opts}" STRATA_CUDA_OK_${akey}_${key} ok)
    if(ok)
      set(built ${archs})
      list(LENGTH archs covered)
    endif()
  else()
    foreach(arch IN LISTS sorted_archs)
      string(REPLACE "sm_" "" num "${arch}")
      foreach(cand IN ITEMS ${arch} sm_90 sm_89 sm_87 sm_86 sm_80 sm_75 sm_72 sm_70 sm_61 sm_60)
        string(REPLACE "sm_" "" cnum "${cand}")
        if(cnum GREATER num)                       # only code the GPU runs: its own or an older architecture's
          continue()
        endif()
        strata_sycl_compiles("-fsycl-targets=nvidia_gpu_${cand};${opts}" STRATA_SYCL_${cand}_${key} ok)
        if(NOT ok AND cand STREQUAL arch AND NOT generic)
          set(generic_flags -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend=nvptx64-nvidia-cuda
                            --cuda-gpu-arch=${cand} ${opts})
          strata_sycl_compiles("${generic_flags}" STRATA_SYCL_GENERIC_${cand}_${key} ok)
          if(ok)
            set(generic ${cand})
          endif()
        endif()
        if(ok)
          list(APPEND built ${cand})
          math(EXPR covered "${covered} + 1")
          math(EXPR sum "${sum} + ${cnum}")
          break()
        endif()
      endforeach()
    endforeach()
  endif()
  list(REMOVE_DUPLICATES built)
  list(SORT built COMPARE NATURAL)
  set(_b_built "${built}" PARENT_SCOPE)
  set(_b_generic "${generic}" PARENT_SCOPE)
  set(_b_covered "${covered}" PARENT_SCOPE)
  set(_b_sum "${sum}" PARENT_SCOPE)
endfunction()

# A string that compares greater for a better toolkit, of fixed-width fields: the GPUs it builds code for, the sum of
# their architectures' numbers (newer code), whether it has cuBLAS, its version.
function(strata_cuda_score covered sum cublas version out)
  set(vnum 0)
  if(version MATCHES "^([0-9]+)\\.([0-9]+)")
    math(EXPR vnum "${CMAKE_MATCH_1} * 100 + ${CMAKE_MATCH_2}")
  endif()
  set(cublas_bit 0)
  if(cublas)
    set(cublas_bit 1)
  endif()
  string(LENGTH "${covered}" l)
  string(SUBSTRING "000${covered}" ${l} 3 f1)
  string(LENGTH "${sum}" l)
  string(SUBSTRING "000000${sum}" ${l} 6 f2)
  string(LENGTH "${vnum}" l)
  string(SUBSTRING "00000${vnum}" ${l} 5 f4)
  set(${out} "${f1}${f2}${cublas_bit}${f4}" PARENT_SCOPE)
endfunction()

# Tries toolkit `dir` for `archs` (each GPU's, or with `explicit` the architectures asked for, every one or none).
# Sets in the caller: _t_opts (the compile options), _t_str (them joined), _t_archs (the code it builds), _t_score (a
# string that compares greater for a better toolkit), _t_note (a line for the report).
function(strata_cuda_try dir archs explicit driver)
  set(_t_score "" PARENT_SCOPE)
  set(opts "--cuda-path=${dir}")
  strata_cuda_ptx("${dir}" "${driver}" ptx toolkit_ptx)
  if(NOT toolkit_ptx)
    set(_t_note "clang does not take it" PARENT_SCOPE)
    return()
  endif()
  if(ptx)
    list(APPEND opts "--cuda-feature=+ptx${ptx}")
  endif()
  string(JOIN " " str ${opts})
  string(MD5 key "${str}")
  string(SUBSTRING "${key}" 0 8 key)
  strata_cuda_builds("${opts}" "${archs}" "${explicit}" "${key}")
  set(built "${_b_built}")
  set(generic "${_b_generic}")
  set(covered "${_b_covered}")
  set(sum "${_b_sum}")
  strata_cuda_has_cublas("${dir}" cublas)
  strata_cuda_version("${dir}" version)
  strata_cuda_score("${covered}" "${sum}" "${cublas}" "${version}" score)
  set(_t_score "${score}" PARENT_SCOPE)
  set(_t_opts "${opts}" PARENT_SCOPE)
  set(_t_str "${str}" PARENT_SCOPE)
  set(_t_archs "${built}" PARENT_SCOPE)
  set(_t_generic "${generic}" PARENT_SCOPE)
  set(_t_cublas "${cublas}" PARENT_SCOPE)
  set(_t_version "${version}" PARENT_SCOPE)
  if(ptx)
    set(ptx_note ", PTX ${ptx} for the driver")
  else()
    set(ptx_note "")
  endif()
  if(built)
    set(code "code for ${built}")
  else()
    set(code "no code these GPUs run")
  endif()
  if(cublas)
    set(cb "cuBLAS")
  else()
    set(cb "no cuBLAS")
  endif()
  set(_t_note "CUDA ${version}: ${code}, ${cb}${ptx_note}" PARENT_SCOPE)
  list(LENGTH archs n_archs)
  set(_t_missing "" PARENT_SCOPE)
  if(covered LESS n_archs)
    set(_t_missing "${covered} of the ${n_archs}" PARENT_SCOPE)
  endif()
endfunction()

# Chooses the toolkit for `archs` (explicit: those exactly; else this PC's GPUs').  Sets in the caller:
# _strata_cuda_path, _strata_cuda_root, _strata_cuda_opts, _strata_cuda_str, _strata_ckey, _strata_cuda_built (the
# architectures it builds code for), _strata_cuda_generic (the one of them built through the generic target, or "")
# and _strata_cuda_cublas.
function(strata_cuda_choose archs explicit)
  file(WRITE "${CMAKE_BINARY_DIR}/strata_ptx_probe.cpp" "int main() { return 0; }\n")
  strata_cuda_driver_version(driver)
  strata_cuda_candidates(dirs)
  if(NOT dirs)
    message(FATAL_ERROR "contrib: no CUDA toolkit found (NVIDIA's CUDA toolkit; STRATA_CUDA_PATH names one)")
  endif()
  set(best "")
  set(best_score "")
  foreach(dir IN LISTS dirs)
    strata_cuda_try("${dir}" "${archs}" "${explicit}" "${driver}")
    message(STATUS "contrib: CUDA toolkit ${dir}: ${_t_note}")
    if(_t_score AND (NOT best_score OR _t_score STRGREATER best_score))
      set(best "${dir}")
      set(best_score "${_t_score}")
      set(best_opts "${_t_opts}")
      set(best_str "${_t_str}")
      set(best_archs "${_t_archs}")
      set(best_generic "${_t_generic}")
      set(best_cublas "${_t_cublas}")
      set(best_version "${_t_version}")
      set(best_missing "${_t_missing}")
    endif()
  endforeach()
  if(NOT best OR NOT best_archs)
    message(FATAL_ERROR "contrib: no CUDA toolkit here builds code for the NVIDIA GPUs ${archs} (one that has them, "
                        "or STRATA_CUDA_ARCHS for others)")
  endif()
  if(best_missing)   # CUDA 13 builds no Pascal or Volta (sm_6x, sm_70) code, for one: a toolkit that still has it does
    message(WARNING "contrib: the CUDA toolkit taken builds code for ${best_missing} NVIDIA GPUs (${archs}): "
                    "a GPU without code is not used; a CUDA toolkit that still has its architecture builds it")
  endif()
  strata_cuda_root("${best}" root)
  string(MD5 key "${best_str}")
  string(SUBSTRING "${key}" 0 8 key)
  message(STATUS "contrib: the CUDA toolkit ${best} (CUDA ${best_version}) for the NVIDIA code and cuBLAS")
  set(_strata_cuda_path "${best}" PARENT_SCOPE)
  set(_strata_cuda_root "${root}" PARENT_SCOPE)
  set(_strata_cuda_opts "${best_opts}" PARENT_SCOPE)
  set(_strata_cuda_str "${best_str}" PARENT_SCOPE)
  set(_strata_ckey "${key}" PARENT_SCOPE)
  set(_strata_cuda_built "${best_archs}" PARENT_SCOPE)
  set(_strata_cuda_generic "${best_generic}" PARENT_SCOPE)
  set(_strata_cuda_cublas "${best_cublas}" PARENT_SCOPE)
endfunction()
